repo: openworm/muscle_model
shortDescription: "Model of c.elegans muscle based on Boyle & Cohen 2008"
coordinator: stephen@openworm.org
documentation: "https://github.com/openworm/muscle_model/blob/master/README.md"
earnable-badges: 
  - "http://www.badgelist.com/OpenWorm/Hodgkin-Huxley-Tutorial-Graduate"
  - "https://www.badgelist.com/OpenWorm/Muscle-Model-Builder"
  - "https://www.badgelist.com/OpenWorm/Muscle-Model-Explorer"
inputs: 
  - openworm/ChannelWorm
keywords: 
  - mathematical model
  - conductance model
  - muscles
  - cells
  - channels
languages: 
  - python
members: 
  - p.gleeson@gmail.com
outputs: 
  - openworm/c302
parent: 
  - openworm/OpenWorm
tests: true
