repo: openworm/muscle_model
shortDescription: "Model of c.elegans muscle"
coordinator: stephen@openworm.org
documentation: "https://github.com/openworm/muscle_model/blob/master/README.md"
earnable-badges: 
  - "http://www.badgelist.com/OpenWorm/Hodgkin-Huxley-Tutorial-Graduate"
  - "https://www.badgelist.com/OpenWorm/Muscle-Model-Builder"
  - "https://www.badgelist.com/OpenWorm/Muscle-Model-Explorer"
gitter: "http://gitter.im/openworm/muscle_model"
inputs: 
  - openworm/ChannelWorm
keywords: 
  - mathematical model
  - conductance model
  - muscles
  - cells
languages: 
  - python
members: 
  - pgleeson@gmail.com
outputs: 
  - openworm/CElegansNeuroML
parent: 
  - openworm/OpenWorm
tests: true
